apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "paathshaala.fullname" . }}
  labels:
    {{- include "paathshaala.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: paathshaala-tls
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "paathshaala.fullname" . }}
                port:
                  number: {{ .Values.service.port }}

