{{- if .Values.redis.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paathshaala-redis-secrets
  labels:
    {{- include "paathshaala.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-99"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: paathshaala-redis-secrets
  dataFrom:
    - extract:
        key: {{ .Values.redis.vaultSecretKey }}
{{- end }}

